// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/19/2024, 12:06:14 AM
const configMerger = require("C:/Users/msu-wone/nuxt-portfolio/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/msu-wone/nuxt-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/msu-wone/nuxt-portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/msu-wone/nuxt-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/msu-wone/nuxt-portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/msu-wone/nuxt-portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/msu-wone/nuxt-portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/msu-wone/nuxt-portfolio/composables/**/*.{js,ts,mjs}","C:/Users/msu-wone/nuxt-portfolio/utils/**/*.{js,ts,mjs}","C:/Users/msu-wone/nuxt-portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/msu-wone/nuxt-portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/msu-wone/nuxt-portfolio/app.config.{js,ts,mjs}"] }));

module.exports = config
